apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: twotier-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        env:
        - name: APP_TITLE
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: APP_TITLE
        - name: BACKEND_HOST
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: BACKEND_HOST